---
- hosts: localhost
  become: true
 
  tasks:
    - name: install nginx
      yum:
        name: nginx
        state: present
 
    - name: start nginx
      service:
        name: nginx
        state: started
        enabled: yes
 
    - name: install git
      yum:
        name: git
        state: present
 
    - name: remove the original html
      shell: |
        mv /usr/share/nginx/html /usr/share/nginx/html.old
 
    - name: clone web template
      git:
        repo: https://github.com/klimenta/webtemplate
        dest: /usr/share/nginx/html
        version: master